#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryMe
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Bot")]
	public partial class botDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPhrase(Phrase instance);
    partial void UpdatePhrase(Phrase instance);
    partial void DeletePhrase(Phrase instance);
    #endregion
		
		public botDataContext() : 
				base(global::TryMe.Properties.Settings.Default.BotConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public botDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public botDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public botDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public botDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Phrase> Phrases
		{
			get
			{
				return this.GetTable<Phrase>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phrase")]
	public partial class Phrase : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _input;
		
		private string _output;
		
		private int _PhraseId;
		
		private System.Nullable<int> _hitCount;
		
		private System.Nullable<System.DateTime> _lastHitDateTime;
		
		private System.Nullable<System.DateTime> _createdDateTime;
		
		private System.Nullable<int> _priority;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OninputChanging(string value);
    partial void OninputChanged();
    partial void OnoutputChanging(string value);
    partial void OnoutputChanged();
    partial void OnPhraseIdChanging(int value);
    partial void OnPhraseIdChanged();
    partial void OnhitCountChanging(System.Nullable<int> value);
    partial void OnhitCountChanged();
    partial void OnlastHitDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlastHitDateTimeChanged();
    partial void OncreatedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedDateTimeChanged();
    partial void OnpriorityChanging(System.Nullable<int> value);
    partial void OnpriorityChanged();
    #endregion
		
		public Phrase()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_input", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string input
		{
			get
			{
				return this._input;
			}
			set
			{
				if ((this._input != value))
				{
					this.OninputChanging(value);
					this.SendPropertyChanging();
					this._input = value;
					this.SendPropertyChanged("input");
					this.OninputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_output", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string output
		{
			get
			{
				return this._output;
			}
			set
			{
				if ((this._output != value))
				{
					this.OnoutputChanging(value);
					this.SendPropertyChanging();
					this._output = value;
					this.SendPropertyChanged("output");
					this.OnoutputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhraseId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PhraseId
		{
			get
			{
				return this._PhraseId;
			}
			set
			{
				if ((this._PhraseId != value))
				{
					this.OnPhraseIdChanging(value);
					this.SendPropertyChanging();
					this._PhraseId = value;
					this.SendPropertyChanged("PhraseId");
					this.OnPhraseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hitCount", DbType="Int")]
		public System.Nullable<int> hitCount
		{
			get
			{
				return this._hitCount;
			}
			set
			{
				if ((this._hitCount != value))
				{
					this.OnhitCountChanging(value);
					this.SendPropertyChanging();
					this._hitCount = value;
					this.SendPropertyChanged("hitCount");
					this.OnhitCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastHitDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastHitDateTime
		{
			get
			{
				return this._lastHitDateTime;
			}
			set
			{
				if ((this._lastHitDateTime != value))
				{
					this.OnlastHitDateTimeChanging(value);
					this.SendPropertyChanging();
					this._lastHitDateTime = value;
					this.SendPropertyChanged("lastHitDateTime");
					this.OnlastHitDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDateTime
		{
			get
			{
				return this._createdDateTime;
			}
			set
			{
				if ((this._createdDateTime != value))
				{
					this.OncreatedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._createdDateTime = value;
					this.SendPropertyChanged("createdDateTime");
					this.OncreatedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priority", DbType="Int")]
		public System.Nullable<int> priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				if ((this._priority != value))
				{
					this.OnpriorityChanging(value);
					this.SendPropertyChanging();
					this._priority = value;
					this.SendPropertyChanged("priority");
					this.OnpriorityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
